package entity;

import java.util.Date;

public class Member {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.id
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.acount
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private String acount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.roleID
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.name
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.nickName
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.gender
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.birth
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private Date birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.country
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.city
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.address
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.latitude
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.longitude
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.telephone
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.email
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.idcard
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.blog
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private String blog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.is_lock
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private Integer isLock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.auditState
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private Integer auditstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.registTime
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private Date registtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.level
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.lastLoginTime
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private Date lastlogintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.loginFailNumber
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private Integer loginfailnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.salt
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.password
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.introduce
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private String introduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.remark
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.language
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private String language;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.id
     *
     * @return the value of member.id
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.id
     *
     * @param id the value for member.id
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.acount
     *
     * @return the value of member.acount
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public String getAcount() {
        return acount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.acount
     *
     * @param acount the value for member.acount
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setAcount(String acount) {
        this.acount = acount == null ? null : acount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.roleID
     *
     * @return the value of member.roleID
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.roleID
     *
     * @param roleid the value for member.roleID
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.name
     *
     * @return the value of member.name
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.name
     *
     * @param name the value for member.name
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.nickName
     *
     * @return the value of member.nickName
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.nickName
     *
     * @param nickname the value for member.nickName
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.gender
     *
     * @return the value of member.gender
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.gender
     *
     * @param gender the value for member.gender
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.birth
     *
     * @return the value of member.birth
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.birth
     *
     * @param birth the value for member.birth
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.country
     *
     * @return the value of member.country
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.country
     *
     * @param country the value for member.country
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.city
     *
     * @return the value of member.city
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.city
     *
     * @param city the value for member.city
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.address
     *
     * @return the value of member.address
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.address
     *
     * @param address the value for member.address
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.latitude
     *
     * @return the value of member.latitude
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.latitude
     *
     * @param latitude the value for member.latitude
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.longitude
     *
     * @return the value of member.longitude
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.longitude
     *
     * @param longitude the value for member.longitude
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.telephone
     *
     * @return the value of member.telephone
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.telephone
     *
     * @param telephone the value for member.telephone
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.email
     *
     * @return the value of member.email
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.email
     *
     * @param email the value for member.email
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.idcard
     *
     * @return the value of member.idcard
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.idcard
     *
     * @param idcard the value for member.idcard
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.blog
     *
     * @return the value of member.blog
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public String getBlog() {
        return blog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.blog
     *
     * @param blog the value for member.blog
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setBlog(String blog) {
        this.blog = blog == null ? null : blog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.is_lock
     *
     * @return the value of member.is_lock
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public Integer getIsLock() {
        return isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.is_lock
     *
     * @param isLock the value for member.is_lock
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setIsLock(Integer isLock) {
        this.isLock = isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.auditState
     *
     * @return the value of member.auditState
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public Integer getAuditstate() {
        return auditstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.auditState
     *
     * @param auditstate the value for member.auditState
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setAuditstate(Integer auditstate) {
        this.auditstate = auditstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.registTime
     *
     * @return the value of member.registTime
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public Date getRegisttime() {
        return registtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.registTime
     *
     * @param registtime the value for member.registTime
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setRegisttime(Date registtime) {
        this.registtime = registtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.level
     *
     * @return the value of member.level
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.level
     *
     * @param level the value for member.level
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.lastLoginTime
     *
     * @return the value of member.lastLoginTime
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public Date getLastlogintime() {
        return lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.lastLoginTime
     *
     * @param lastlogintime the value for member.lastLoginTime
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setLastlogintime(Date lastlogintime) {
        this.lastlogintime = lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.loginFailNumber
     *
     * @return the value of member.loginFailNumber
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public Integer getLoginfailnumber() {
        return loginfailnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.loginFailNumber
     *
     * @param loginfailnumber the value for member.loginFailNumber
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setLoginfailnumber(Integer loginfailnumber) {
        this.loginfailnumber = loginfailnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.salt
     *
     * @return the value of member.salt
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.salt
     *
     * @param salt the value for member.salt
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.password
     *
     * @return the value of member.password
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.password
     *
     * @param password the value for member.password
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.introduce
     *
     * @return the value of member.introduce
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.introduce
     *
     * @param introduce the value for member.introduce
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.remark
     *
     * @return the value of member.remark
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.remark
     *
     * @param remark the value for member.remark
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.language
     *
     * @return the value of member.language
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.language
     *
     * @param language the value for member.language
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }
}