package entity;

import java.util.Date;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.id
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.name
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.size
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private Integer size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.start_time
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.end_time
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.is_lock
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private Integer isLock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.sort
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.remark
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.id
     *
     * @return the value of role.id
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.id
     *
     * @param id the value for role.id
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.name
     *
     * @return the value of role.name
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.name
     *
     * @param name the value for role.name
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.size
     *
     * @return the value of role.size
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.size
     *
     * @param size the value for role.size
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.start_time
     *
     * @return the value of role.start_time
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.start_time
     *
     * @param startTime the value for role.start_time
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.end_time
     *
     * @return the value of role.end_time
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.end_time
     *
     * @param endTime the value for role.end_time
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.is_lock
     *
     * @return the value of role.is_lock
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public Integer getIsLock() {
        return isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.is_lock
     *
     * @param isLock the value for role.is_lock
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setIsLock(Integer isLock) {
        this.isLock = isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.sort
     *
     * @return the value of role.sort
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.sort
     *
     * @param sort the value for role.sort
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.remark
     *
     * @return the value of role.remark
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.remark
     *
     * @param remark the value for role.remark
     *
     * @mbggenerated Tue Nov 15 22:11:44 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}